version: 2
jobs:
  build:
    docker:
      - image: viert/m68kbuild:latest
    working_directory: /tmp/build
    steps:
      - checkout
      - run:
          name: Building VM68k ROM file
          command: make
      - store_artifacts:
          path: /tmp/build/vm68krom.bytes
