version: 2
general:
  artifacts:
    - "vm68krom.bytes"
jobs:
  build:
    docker: 
      - image: ubuntu:xenial
    steps:
      - checkout
      - run: 
          name: Preparing APT
          command: apt update
      - run: 
          name: Installing packages 
          command: apt -y install gcc-m68k-linux-gnu binutils-m68k-linux-gnu make
      - run:
          name: Building VM68k ROM file
          command: make