version: 2
jobs:
  build:
    docker: 
      - image: ubuntu:xenial
    working_directory: /tmp/build
    steps:
      - checkout
      - run: 
          name: Preparing APT
          command: apt update
      - run: 
          name: Installing packages 
          command: apt -y install gcc-m68k-linux-gnu binutils-m68k-linux-gnu make
      - run:
          name: Building VM68k ROM file
          command: make
      - store_artifacts:
          path: /tmp/build/vm68krom.bytes